#!/bin/sh

set -euo pipefail

token=$(cat /run/secrets/restic_powerup_homeassistant_token)

apicall() {
    local path="$1"
    shift

    curl \
        --connect-to homeassistant.home.arpa::homeassistant: \
        -f --silent \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" \
        "https://homeassistant.home.arpa/api/$path" \
        "$@"
}

read -r host
case "$host" in
restic-backup-1.home.arpa)
    # This is always connected.
    exit 0
    ;;
restic-backup-2.home.arpa)
    entity_id="switch.michael_dect"
    ;;
*)
    echo "unsupported host: $host"
    exit 1
    ;;
esac

current_state=$(apicall "states/$entity_id" -X GET | jq -re '.state')

if [ "$current_state" == "on" ]; then
    echo "$host is already online"
    exit 0
fi

echo "powerup $host (current=$current_state)"
apicall services/switch/turn_on \
    -X POST \
    --data "{\"entity_id\":\"$entity_id\"}"
