{
 "title": "Home Assistant",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"power\")\n  |> filter(fn: (r) => r.entity_id == \"smartmeter_power\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"humidity\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "temp = from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"temperature\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))\n\nclimate = from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.domain == \"climate\")\n    |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.current_temperature,\n    }))\n\nunion(tables:[temp, climate])"
    }
   ]
  },
  {
   "title": "Pressures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"pressure\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"battery\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"carbon_dioxide\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}