{
 "title": "LXD",
 "description": "Overview of LXD instances",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(lxd_procs_total, job)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(lxd_procs_total{job=\"$job\"}, project)"
    }
   },
   {
    "name": "name",
    "label": "Instance",
    "query": {
     "query": "label_values(lxd_procs_total{job=\"$job\",project=\"$project\"}, name)"
    }
   },
   { "name": "top", "label": "Top", "query": "3, 4, 5, 10" }
  ]
 },
 "panels": [
  { "title": "Project overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top ${top} memory usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\"})-sum(topk(${top}, lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\"}))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} disk usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, lxd_filesystem_size_bytes{job=\"$job\",project=\"$project\"} - lxd_filesystem_free_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(lxd_filesystem_size_bytes{job=\"$job\",project=\"$project\"})-sum(lxd_filesystem_free_bytes{job=\"$job\",project=\"$project\"})-sum(topk(${top}, lxd_filesystem_size_bytes{job=\"$job\",project=\"$project\"} - lxd_filesystem_free_bytes{job=\"$job\",project=\"$project\"}))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Project Memory Usage",
   "type": "timeseries",
   "description": "Memory usage overview for the whole project",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\"} - lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "sum(lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(lxd_memory_Swap_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Project CPU Usage",
   "type": "timeseries",
   "description": "CPU usage overview for the whole project",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(lxd_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\"}[$__rate_interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Project Disk Space Usage",
   "type": "timeseries",
   "description": "Disk space used for the whole project",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum((lxd_filesystem_avail_bytes{job=\"$job\",project=\"$project\"}) * 100) / sum(lxd_filesystem_size_bytes{job=\"$job\",project=\"$project\"}))",
     "legendFormat": "Disk used"
    }
   ]
  },
  {
   "title": "Project Network Traffic",
   "type": "timeseries",
   "description": "Network traffic overview for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(lxd_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*-8",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(lxd_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Project Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read or written per second for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(lxd_disk_read_bytes_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))*-1",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(rate(lxd_disk_written_bytes_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Project Disk IOps Completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(lxd_disk_reads_completed_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))*-1",
     "legendFormat": "Reads completed"
    },
    {
     "expr": "sum(rate(lxd_disk_writes_completed_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Writes completed"
    }
   ]
  },
  {
   "title": "Project Running processes",
   "type": "timeseries",
   "description": "Number of running processes for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(lxd_procs_total{project=\"$project\"})",
     "legendFormat": "Processes"
    }
   ]
  },
  { "title": "Instance: $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "name" },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(lxd_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(lxd_memory_MemTotal_bytes{job=\"$job\",project=\"$project\",name=\"$name\"} - lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\",name=\"$name\"} - lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(lxd_memory_Cached_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "sum(lxd_memory_MemFree_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(lxd_memory_Swap_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(lxd_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])*8",
     "legendFormat": "RX {{device}}"
    },
    {
     "expr": "rate(lxd_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])*8",
     "legendFormat": "TX {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((lxd_filesystem_avail_bytes{job=\"$job\",project=\"$project\",name=\"$name\"} * 100) / lxd_filesystem_size_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(lxd_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(lxd_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors and Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(lxd_network_receive_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - RX errors"
    },
    {
     "expr": "rate(lxd_network_transmit_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - TX errors"
    },
    {
     "expr": "rate(lxd_network_receive_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - RX drop"
    },
    {
     "expr": "rate(lxd_network_transmit_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - TX drop"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(lxd_disk_reads_completed_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(lxd_disk_writes_completed_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(lxd_disk_read_bytes_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "rate(lxd_disk_written_bytes_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Running processes",
   "type": "timeseries",
   "description": "Number of running processes in the instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lxd_procs_total{project=\"$project\",name=\"$name\"}",
     "legendFormat": "Processes"
    }
   ]
  }
 ]
}