#!/bin/bash

set -euo pipefail

backbone_if="eth0"
thread_if="wpan0"
otbr_forward_ingress_chain="OTBR_FORWARD_INGRESS"
otbr_forward_egress_chain="OTBR_FORWARD_EGRESS"

ipset create -exist otbr-ingress-deny-src hash:net family inet6
ipset create -exist otbr-ingress-deny-src-swap hash:net family inet6
ipset create -exist otbr-ingress-allow-dst hash:net family inet6
ipset create -exist otbr-ingress-allow-dst-swap hash:net family inet6

ip6tables -N $otbr_forward_ingress_chain
ip6tables -I FORWARD 1 -o $thread_if -j $otbr_forward_ingress_chain

ip6tables -A $otbr_forward_ingress_chain -m pkttype --pkt-type unicast -i "$thread_if" -j DROP
ip6tables -A $otbr_forward_ingress_chain -m set --match-set otbr-ingress-deny-src src -j DROP
ip6tables -A $otbr_forward_ingress_chain -m set --match-set otbr-ingress-allow-dst dst -j ACCEPT
ip6tables -A $otbr_forward_ingress_chain -m pkttype --pkt-type unicast -i "$backbone_if" -j ACCEPT
ip6tables -A $otbr_forward_ingress_chain -m pkttype --pkt-type unicast -j DROP
ip6tables -A $otbr_forward_ingress_chain -j ACCEPT

ip6tables -N $otbr_forward_egress_chain
ip6tables -I FORWARD 2 -i $thread_if -j $otbr_forward_egress_chain
ip6tables -A $otbr_forward_egress_chain -j ACCEPT

/usr/sbin/mdnsd -debug &
sleep 2

exec otbr-agent \
	-v \
	-d 7 \
	-s \
	-I "$thread_if" \
	-B "$backbone_if" \
	spinel+hdlc+uart:///dev/serial/by-id/usb-Nordic_Semiconductor_ASA_OpenThread_CoProcessor_3804D0A373C4BD19-if00 \
	"trel://$backbone_if"
