http:
  routers:
    router0:
      entryPoints:
        - websecure
      service: service-immich
      rule: Host(`immich.mzimmermann.info`)
      tls:
        certResolver: myresolver

  services:
    service-immich:
      loadBalancer:
        servers:
          - url: http://immich-server:2283/
