tls:
  certificates:
    - certFile: /run/secrets/immich_https_cert
      keyFile: /run/secrets/immich_https_key

http:
  routers:
    router-mzimmermanninfo:
      entryPoints:
        - websecure
      service: service-immich
      rule: Host(`immich.mzimmermann.info`)
      tls:
        certResolver: myresolver

    router-homearpa:
      entryPoints:
        - websecure
      service: service-immich
      rule: Host(`immich.home.arpa`)
      tls: {}

  services:
    service-immich:
      loadBalancer:
        servers:
          - url: http://immich-server:2283/
