config:
  ipv4.address: 10.96.96.1/24
  ipv4.firewall: "false"
  ipv4.nat: "true"
  ipv6.address: fd42:78a7:efe7:100d::1/64
  ipv6.firewall: "false"
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
managed: true
status: Created
locations:
  - none
