---
- hosts: homeserver
  vars:
    container_macs: "{{ lookup('container_query', 'containers', pattern='^Network=.*mac=(([a-zA-Z0-9]{2}:){5}[a-zA-Z0-9]{2}).*$') }}"
    container_ips: "{{ lookup('container_query', 'containers', pattern='^Network=.*ip=(\\d+\\.\\d+\\.\\d+\\.\\d+).*$') }}"

  tasks:
    - import_tasks: tasks/systemd-failure-notification.yml
    - import_tasks: tasks/podman.yml
    - import_tasks: tasks/firewall.yml
    - import_tasks: tasks/arp-reply.yml
    - import_tasks: tasks/containers.yml
    - import_tasks: tasks/restic.yml

  handlers:
    - name: reload_nft
      ansible.builtin.systemd:
        name: nftables.service
        state: restarted

    - name: reload_systemd
      ansible.builtin.systemd:
        daemon_reload: true
