{
 "title": "Bind9 Full",
 "description": "Bind9 exporter monitoring",
 "tags": [
  "bind",
  "dns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(bind_up,job)" } },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(bind_up{job=\"$job\"},instance)"
    }
   },
   {
    "name": "view",
    "label": "BIND view",
    "query": {
     "query": "label_values(bind_resolver_query_errors_total, view)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate(bind_incoming_queries_total{instance=\"$node\", job=\"$job\"}[5m]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum (irate(bind_resolver_queries_total{instance=\"$node\", job=\"$job\"}[5m]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Incoming DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(bind_incoming_queries_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outgoing DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(bind_resolver_queries_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
     "legendFormat": "{{ type }} {{ view }}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(bind_incoming_requests_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Responses Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(bind_responses_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Last Reconfiguration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bind_config_time_seconds{instance=\"$node\", job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "BIND Process Start Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bind_boot_time_seconds{instance=\"$node\", job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resolver Query Retries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_retries_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "queries retry {{ view }} "
      }
     ]
    },
    {
     "title": "Querie Issues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_query_duplicates_total{instance=\"$node\", job=\"$job\"}[5m])",
       "legendFormat": "Duplicated queries received"
      },
      {
       "expr": "irate(bind_query_errors_total{instance=\"$node\", job=\"$job\"}[5m])",
       "legendFormat": "{{ error }} queries"
      },
      {
       "expr": "irate(bind_query_recursions_total{instance=\"$node\", job=\"$job\"}[5m])",
       "legendFormat": "Queries causing recursionries received"
      }
     ]
    },
    {
     "title": "Resolver Response Errors Received",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_response_errors_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "{{ error }} {{ view }}"
      }
     ]
    },
    {
     "title": "Resolver Queries Failed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_errors_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "{{ error }} {{ view }}"
      },
      {
       "expr": "irate(bind_resolver_query_edns0_errors_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "EDNS(0) error {{ view }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resolver Query round-trip Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_duration_seconds_bucket{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "{{ le }} round-trip {{ view }}"
      }
     ]
    },
    {
     "title": "Resolver Query round-trip Count / Sum",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_duration_seconds_count{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "count {{ view }} "
      },
      {
       "expr": "irate(bind_resolver_query_duration_seconds_sum{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "sum {{ view }}"
      }
     ]
    },
    {
     "title": "RRSets in Cache Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_cache_rrsets{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "{{ type }} {{ view }}"
      }
     ]
    },
    {
     "title": "Responses Received Truncated / Mismatch / Lame",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_response_truncated_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "truncated {{ view }}"
      },
      {
       "expr": "irate(bind_resolver_response_mismatch_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "mismatch  {{ view }}"
      },
      {
       "expr": "irate(bind_resolver_response_lame_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "lame  {{ view }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNSsec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNSSEC Validation Attempts",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(bind_resolver_dnssec_validation_errors_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m])",
       "legendFormat": "Errors {{ view }}"
      },
      {
       "expr": "sum by (instance, view)(irate(bind_resolver_dnssec_validation_success_total{instance=\"$node\", job=\"$job\",view=~\"$view\"}[5m]))",
       "legendFormat": "Success {{ view }}"
      }
     ]
    }
   ]
  }
 ]
}