{
 "title": "Home Assistant",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "W_value{entity_id=\"smartmeter_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "_g_m__value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "_C_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "__value{device_class=\"humidity\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"humidity\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "__value{device_class=\"battery\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "V_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "ppm_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "hPa_value{device_class=\"atmospheric_pressure\"}",
     "legendFormat": "__auto",
     "query": "from(bucket: \"home-assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> group(columns: [\"entity_id\", \"friendly_name_str\"])\n  |> filter(fn: (r) => r.device_class_str == \"pressure\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      entity_id: r.entity_id,\n      friendly_name_str: r.friendly_name_str,\n      _value: r.value,\n    }))"
    }
   ]
  }
 ]
}