---
- name: Install arp-reply config
  ansible.builtin.copy:
    dest: /etc/arp-reply.yaml
    owner: root
    group: root
    mode: '0644'
    content: |
      ---
      {% for name, ip in container_ips %}
      {% set ip_pub = ip | regex_replace('^10\.88\.42\.(\d+)$', '192.168.43.\\1') %}
      {% if ip_pub != ip %}
      - {{ ip_pub }}
      {% endif %}
      {% endfor %}

- name: Install arp-reply binary
  ansible.builtin.copy:
    src: arp-reply/target/aarch64-unknown-linux-gnu/release/arp-reply
    dest: /usr/local/bin/arp-reply
    owner: root
    group: root
    mode: '0755'

- name: Install arp-reply.service
  ansible.builtin.copy:
    dest: /etc/systemd/system/arp-reply.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=arp-reply
      After=network.target

      [Service]
      Type=simple
      ProtectSystem=full
      ProtectHome=true
      ExecStart=/usr/local/bin/arp-reply -i eth0
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
  notify: reload_systemd

# the default service flushes podmans rules on restart
- name: Create /etc/hosts
  ansible.builtin.copy:
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    content: |
      # Loopback entries; do not change.
      # For historical reasons, localhost precedes localhost.localdomain:
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      # See hosts(5) for proper format and other examples:
      # 192.168.1.10 foo.mydomain.org foo
      # 192.168.1.13 bar.mydomain.org bar

      # 1) we can't see our own arp replies
      # 2) using the internal address is more effecient
      {% for name, ip in container_ips %}
      {% set ip_pub = ip | regex_replace('^10\.88\.42\.(\d+)$', '192.168.43.\\1') %}
      {% if ip_pub != ip %}
      {{ ip }} {{ name }}.home.arpa
      {% endif %}
      {% endfor %}
  notify: reload_systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start arp-reply service
  ansible.builtin.systemd:
    name: arp-reply.service
    enabled: true
    state: restarted
