---
- name: Replace gitmirror.timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/gitmirror.timer
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Starts gitmirror

      [Timer]
      OnCalendar=daily
      RandomizedDelaySec=900
      Persistent=true

      [Install]
      WantedBy=timers.target
  notify: reload_systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start gitmirror.timer
  ansible.builtin.systemd:
    name: gitmirror.timer
    enabled: true
    state: started
