---
- name: Create mount archive service
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-media-archive.mount
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Archive mount
      After=systemd-fsck@dev-disk-by\x2dpartlabel-archive.service
      Requires=systemd-fsck@dev-disk-by\x2dpartlabel-archive.service
      # the documentation says this is implicit but `systemctl show` disagreed
      BindsTo=dev-disk-by\x2dpartlabel-archive.device

      [Mount]
      What=/dev/disk/by-partlabel/archive
      Where=/run/media/archive
      Type=btrfs
      Options=defaults
  notify: reload_systemd

- name: Create mount media service
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-media-media.mount
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Media mount
      After=systemd-fsck@dev-disk-by\x2dpartlabel-media.service
      Requires=systemd-fsck@dev-disk-by\x2dpartlabel-media.service
      # the documentation says this is implicit but `systemctl show` disagreed
      BindsTo=dev-disk-by\x2dpartlabel-media.device

      [Mount]
      What=/dev/disk/by-partlabel/media
      Where=/run/media/media
      Type=ext4
      Options=defaults
  notify: reload_systemd

- name: Create mount roms service
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-media-roms.mount
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=roms mount
      After=systemd-fsck@dev-disk-by\x2duuid-e2c9c743\x2d80a5\x2d4671\x2dbb8e\x2d10a7079c2fa8.service
      Requires=systemd-fsck@dev-disk-by\x2duuid-e2c9c743\x2d80a5\x2d4671\x2dbb8e\x2d10a7079c2fa8.service
      # the documentation says this is implicit but `systemctl show` disagreed
      BindsTo=dev-disk-by\x2duuid-e2c9c743\x2d80a5\x2d4671\x2dbb8e\x2d10a7079c2fa8.device

      [Mount]
      What=/dev/disk/by-uuid/e2c9c743-80a5-4671-bb8e-10a7079c2fa8
      Where=/run/media/roms
      Type=btrfs
      Options=defaults
  notify: reload_systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
