---
- name: Create mount service
  ansible.builtin.copy:
    dest: /etc/systemd/system/run-media-resticbackup.mount
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Restic backup mount¸
      After=systemd-fsck@dev-disk-by\x2dpartlabel-restic\x2dbackup.service
      Requires=systemd-fsck@dev-disk-by\x2dpartlabel-restic\x2dbackup.service
      # the documentation says this is implicit but `systemctl show` disagreed
      BindsTo=dev-disk-by\x2dpartlabel-restic\x2dbackup.device
      PartOf=restic-backup-1.service
      StopWhenUnneeded=true

      [Mount]
      What=/dev/disk/by-partlabel/restic-backup
      Where=/run/media/resticbackup
      Type=ext4
      Options=defaults,data=journal
  notify: reload_systemd

- name: Replace syncthing-rsync.timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/restic-autobackup.timer
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Starts restic autobackup

      [Timer]
      OnCalendar=weekly
      RandomizedDelaySec=900
      Persistent=true

      [Install]
      WantedBy=timers.target
  notify: reload_systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start restic-autobackup.timer
  ansible.builtin.systemd:
    name: restic-autobackup.timer
    enabled: true
    state: started
