---

# Based on: https://wiki.archlinux.org/title/systemd#Notifying_about_failed_services

- name: Create service.d
  ansible.builtin.file:
    mode: '0755'
    path: /etc/systemd/system/service.d
    state: directory

- name: Create failure-notification override directory
  ansible.builtin.file:
    mode: '0755'
    path: /etc/systemd/system/failure-notification@.service.d
    state: directory

# prevent recursion when failure-notification fails
- name: Create empty failure-notification override
  ansible.builtin.copy:
    dest: /etc/systemd/system/failure-notification@.service.d/toplevel-override.conf
    owner: root
    group: root
    mode: '0644'
    content: ''
  notify: reload_systemd

- name: Create failure notification script
  ansible.builtin.copy:
    dest: /usr/local/bin/failure-notification
    owner: root
    group: root
    mode: '0755'
    content: |
      #!/bin/bash
      set -uo pipefail

      status=1

      # even if the service is up, it may not be listening to the port yet.
      # # So lets retry a few times
      for i in {1..3}; do
          curl "https://gotify.home.arpa/message?token=${GOTIFY_APP_TOKEN}" "$@" && status=0 && break
          sleep 2
      done

      exit "$status"

- name: Create failure notification service
  ansible.builtin.copy:
    dest: /etc/systemd/system/failure-notification@.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Send a notification about a failed systemd unit
      After=network.target gotify.service
      Requires=gotify.service

      [Service]
      EnvironmentFile=/opt/container-secrets/gotify/systemd-token.env
      Type=simple
      ExecStart=/usr/local/bin/failure-notification -F "title=homeserver systemd" -F "message=%i failed" -F "priority=5"

  notify: reload_systemd

# override for all services
- name: Create toplevel override
  ansible.builtin.copy:
    dest: /etc/systemd/system/service.d/toplevel-override.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      OnFailure=failure-notification@%n
  notify: reload_systemd
