#!/bin/sh

set -euo pipefail

targz="$1"

error() {
        echo "$@" >&2
}

current_rootpart=$(cat /proc/cmdline | tr ' ' '\n' | grep -m1 '^root=/dev/mmcblk1p' | sed 's|^root=/dev/mmcblk1p||')
case $current_rootpart in
        6)
                current_slot=0
                next_slot=1
                next_part=7
                ;;
        7)
                current_slot=1
                next_slot=0
                next_part=6
                ;;
        *)
                error "invalid rootpart: $current_rootpart"
                exit 1
                ;;
esac

echo "$current_slot(mmcblk1p$current_rootpart) -> $next_slot(mmcblk1p$next_part)"

error "mount boot partition rw"
mount -o rw,remount /boot

boot_dir="/boot/boot_${next_slot}"
if [ -d "$boot_dir" ];then
        error "delete old boot dir"
        rm -r "$boot_dir"
fi

error "extract new boot dir"
tar -C /boot -xf "$targz" ./boot
mv /boot/boot "$boot_dir"

error "extract new rootfs"
tar -O  -xf "$targz" ./root.squashfs | dd bs=10M of="/dev/mmcblk1p${next_part}"

error "update boot.txt"
sed -i "s/^\\(setenv slot\\)\\s[0-9]\\s*/\\1 ${next_slot}/g" /boot/boot.txt
sed -i "s/^\\(setenv slot_mmcblk\\)\\s[0-9]\\s*/\\1 ${next_part}/g" /boot/boot.txt
(cd /boot && ./mkscr)

error "done"
