#!/bin/sh

set -euo pipefail

targz="$1"

error() {
        echo "$@" >&2
}

current_slot=$(cat /proc/cmdline | tr ' ' '\n' | grep -m1 '^root=PARTLABEL=rootfs' | sed 's|^root=PARTLABEL=rootfs||')
case $current_slot in
        0)
                next_slot=1
                ;;
        1)
                next_slot=0
                ;;
        *)
                error "invalid slot: $current_slot"
                exit 1
                ;;
esac

echo "$current_slot -> $next_slot"

error "mount boot partition rw"
mount -o rw,remount /boot

boot_dir="/boot/boot_${next_slot}"
if [ -d "$boot_dir" ];then
        error "delete old boot dir"
        rm -r "$boot_dir"
fi

error "extract new boot dir"
tar -C /boot -xf "$targz" ./boot
mv /boot/boot "$boot_dir"

error "extract new rootfs"
tar -O  -xf "$targz" ./root.squashfs | dd bs=10M of="/dev/disk/by-partlabel/rootfs${next_slot}"

error "update boot.txt"
sed -i "s/^\\(setenv slot\\)\\s[0-9]\\s*/\\1 ${next_slot}/g" /boot/boot.txt
(cd /boot && ./mkscr)

error "done"
