#!/bin/bash

set -xeuo pipefail

teardown() {
	echo "Exit"
	exit 0
}
trap teardown SIGTERM

echo "Init"

ip link set dev lo up
ip link set dev eth0 up
ip link set dev eth1 up

ip addr add dev eth0 fe80::64
ip addr add dev eth1 192.168.41.101/24

ip route add default via 192.168.41.100
ip -6 route add default via fe80::1 dev eth0

jool instance add --netfilter --pool6 fd33:1491:4cfa:f069::/64
jool global update lowest-ipv6-mtu 1500
jool pool4 add 192.168.41.101 33000-65535 --tcp
jool pool4 add 192.168.41.101 33000-65535 --udp
jool pool4 add 192.168.41.101 33000-65535 --icmp

sleep infinity &
wait
