http:
  routers:
    router0:
      entryPoints:
        - websecure
      service: service-jellyfin
      rule: Host(`jellyfin.mzimmermann.info`)
      tls:
        certResolver: myresolver

  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://jellyfin:8096/
