tls:
  certificates:
    - certFile: /run/secrets/jellyfin_https_cert
      keyFile: /run/secrets/jellyfin_https_key

http:
  routers:
    router-mzimmermanninfo:
      entryPoints:
        - websecure
      service: service-jellyfin
      rule: Host(`jellyfin.mzimmermann.info`)
      tls:
        certResolver: myresolver

    router-homearpa:
      entryPoints:
        - websecure
      service: service-jellyfin
      rule: Host(`jellyfin.home.arpa`)
      tls: {}

  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://jellyfin:8096/
