apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    uid: 'rjl7EP47k'
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: local
      defaultBucket: default-bucket
      httpMode: 'POST'
      maxSeries: 1000000
    secureJsonData:
      token: $INFLUXDB_TOKEN
