apiVersion: 1

datasources:
  - name: VictoriaMetrics-Prometheus
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
