configs:
  noreply@bitwarden.home.arpa:
    "*@*":
      urls:
        - gotifys://gotify/{{ mailrise_gotify_token }}
      mailrise:
        title_template: "bitwarden: $subject"
        body_template: |
          To: $to
          $body
        body_format: text

prefer_plain: true
