devices:
  data:
    path: /var/lib/influxdb2
    pool: default
    source: influxdb
    type: disk
  config:
    path: /media/config
    readonly: "true"
    shift: "true"
    source: /media/config/influxdb
    type: disk

profiles:
  - private

config:
  environment.DOCKER_INFLUXDB_INIT_MODE: setup
  environment.DOCKER_INFLUXDB_INIT_USERNAME: admin
  environment.DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
  environment.DOCKER_INFLUXDB_INIT_ORG: local
  environment.DOCKER_INFLUXDB_INIT_BUCKET: default-bucket
  environment.INFLUXD_TLS_CERT: /media/config/server.crt
  environment.INFLUXD_TLS_KEY: /media/config/server.key
  volatile.eth0.hwaddr: 00:16:3e:64:7c:f8
