#!/bin/sh

set -xeuo pipefail

xrestic() {
    local host="$1"
    shift

    # wakeup
    echo "$host" | nc -v restic-powerup 8001

    # wait for server to bind to port
    timeout 120 sh -c "while ! nc -z '$host' 8000; do sleep 0.5; done"

    restic \
        -r "rest:https://$host:8000/restic" \
        --cacert "/media/config/ca.pem" \
        --tls-client-cert "/media/config/ssl_combined.pem" \
        --verbose \
        --password-file "/media/config/credentials" \
        "$@"
}

xrestic_backup() {
    local host="$1"
    xrestic "$host" backup /media/data
}

xrestic_backup restic-backup-2.home.arpa
xrestic_backup restic-backup-1.home.arpa
