tls:
  certificates:
    - certFile: /media/config/jellyfin.crt
      keyFile: /media/config/jellyfin.key
  options:
    default:
      sniStrict: true

http:
  routers:
    router0:
      entryPoints:
        - websecure
      service: service-jellyfin
      rule: Host(`jellyfin.home.arpa`)
      tls: {}

  services:
    service-jellyfin:
      loadBalancer:
        servers:
          - url: http://jellyfin:8096/
