#!/usr/bin/busybox ash

set -euo pipefail

script=$(readlink -f "$0")
scriptdir=$(dirname "$script")

cd "$scriptdir"

alias lxc='ssh root@192.168.43.2 lxc'

lxc config show > config.yml

networks=$(lxc network list --format yaml | yq -r '.[] | select(.managed) | .name')
profiles=$(lxc profile list --format yaml | yq -r '.[].name')
projects=$(lxc project list --format yaml | yq -r '.[].name')
storages=$(lxc storage list --format yaml | yq -r '.[].name')

mkdir -p networks
mkdir -p networks/forwards
for network in $networks ; do
	lxc network show "$network" | yq 'del(.used_by)' > "networks/$network.yaml"
	forwards=$(lxc network forward list "$network" --format yaml)
	num_forwards=$(echo "$forwards" | yq '. | length')

	if [ "$num_forwards" != "0" ]; then
		echo -n "$forwards" > "networks/forwards/$network.yaml"
	fi
done

mkdir -p projects
for project in $projects ; do
	lxc project show "$project" | yq 'del(.used_by)' > "projects/$project.yaml"
done

mkdir -p profiles
for profile in $profiles ; do
	lxc profile show "$profile" | yq 'del(.used_by)' > "profiles/$profile.yaml"
done

mkdir -p storages
for storage in $storages ; do
	lxc storage show "$storage" | yq 'del(.used_by)' > "storages/$storage.yaml"

	storagedir="storages/$storage"
	mkdir -p "$storagedir"

	volumes=$(lxc storage volume list --format yaml "$storage" \
		| yq -r \
		'.[] | select(.type == "custom") | select(.name | contains("/") | not) | .name')
	for volume in $volumes ; do
		lxc storage volume show "$storage" "custom/$volume" \
			| yq 'del(.used_by)' \
			> "$storagedir/$volume.yaml"
	done
done
