#!/usr/bin/env python3

import subprocess
import requests
import time
import json

server = subprocess.Popen(["python", "-m", "immich_ml"])
time.sleep(10)


def load_clip():
    entries = {"clip": {"textual": {"modelName": "ViT-B-32__openai"}}}

    r = requests.post(
        "http://127.0.0.1:3003/predict",
        data={
            "entries": json.dumps(entries),
            "text": "test",
        },
    )
    print(r.text)

def load_buffalo():
    entries = {
            "facial-recognition": {
                "recognition": {
                    "modelName": "buffalo_l",
                    "options": {"minScore": 0.7}
                },
                "detection": {
                    "modelName": "buffalo_l"
                },
            }
    }

    with open('/mnt/jpeg.jpg', 'rb') as file:
        data = file.read()

    r = requests.post(
        "http://127.0.0.1:3003/predict",
        data={
            "entries": json.dumps(entries),
        },
        files={"image": data}
    )
    print(r.text)

load_clip()
load_buffalo()

