config:
  environment.LXDOCKER_UDHCPC_NOPREFIXROUTE: "1"
  security.idmap.isolated: "true"
description: private network config
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdpriv0
    security.mac_filtering: "true"
    security.port_isolation: "true"
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: private
