#!/bin/sh

set -euo pipefail

script=$(readlink -f "$0")
scriptdir=$(dirname "$script")
repo=$(realpath "$scriptdir/..")

build="$repo/build/mkimage"
mkdir -p "$build"

cd "$repo/third_party/aports"
sh "$repo/third_party/aports/scripts/mkimage.sh" \
	--tag edge \
	--outdir "$build" \
	--arch aarch64 \
	--repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
	--repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
	--repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
	"$@"
