#!/bin/sh

set -euo pipefail

token=$(cat /media/config/homeassistant-token)

apicall() {
    local path="$1"
    shift

    curl \
	-f --silent \
	-H "Authorization: Bearer $token" \
	-H "Content-Type: application/json" \
	"https://homeassistant.home.arpa:8123/api/$path" \
	"$@"
}

read -r host
case "$host" in
restic-backup-1.home.arpa)
    entity_id="switch.ikea_of_sweden_tradfri_control_outlet_fe7916fe_on_off"
    ;;
restic-backup-2.home.arpa)
    entity_id="switch.michael_dect"
    ;;
*)
    echo "unsupported host: $host"
    exit 1
    ;;
esac

current_state=$(apicall "states/$entity_id" -X GET | jq -re '.state')

if [ "$current_state" == "on" ]; then
    echo "$host is already online"
    exit 0
fi

echo "powerup $host (current=$current_state)"
apicall services/switch/turn_on \
	-X POST \
	--data "{\"entity_id\":\"$entity_id\"}"
