FROM docker.io/golang:1.20-alpine AS golang
RUN go install github.com/mailhog/mailhog@e6fa06877ef61ea82bbef234d94bdc75cca478d1

FROM docker.io/alpine:latest
RUN apk add --no-cache \
    ca-certificates \
    curl \
    fuse \
    jq \
    netcat-openbsd \
    openssh-client \
    openssh-server \
    rclone \
    restic \
    samba \
    socat \
    tzdata
COPY --from=golang /go/bin/mailhog /usr/local/bin/
