config:
  security.shifted: "true"
  volatile.idmap.last: '[]'
  volatile.idmap.next: '[]'
description: ""
name: homeassistant-config
type: custom
location: none
content_type: filesystem
project: default
