name: container-images

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push restic-powerup
        uses: docker/build-push-action@v3
        with:
          context: container-images
          file: container-images/Containerfile.restic-powerup
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/m1cha/restic-powerup:latest

      - name: Build and push restic-autobackup
        uses: docker/build-push-action@v3
        with:
          context: container-images
          file: container-images/Containerfile.restic-autobackup
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/m1cha/restic-autobackup:latest
