no-resolv
no-hosts
no-poll
domain-needed
bogus-priv
address=/unifi/10.93.128.2
dhcp-option=option:dns-server,10.93.128.3

interface=eth0
bind-dynamic

log-dhcp
log-debug
log-facility=-

dhcp-range=eth0,10.93.200.10,10.93.200.200,1h

# 10.93.128.2
dhcp-option=43,01:04:0A:5D:80:02
